### ISSUE TITLE
Unable to view Video Track for the receiver in the room

### ISSUE THREAD

**Issue by a1nouru** [twilio/video-quickstart-ios#441] opened 2019-12-02 20:17 UTC
Hi,

I am running into an issue whereby when participants join a room one of the participants is not able to receive the video track for the other person although the audio is available all the time. This issue happens randomly and I am currently unable to reproduce it. 

Any ideas on whether this could be caused by the **asynchronous architecture** or maybe the current participants did not leave their previous rooms correctly(did not get disconnected properly) so their video session was not released? Not sure. 

Thanks :)

**Comment by ceaglest** [comment] 2019-12-02 20:53
Hi @a1nouru,

I think this is a duplicate of #384 which I just responded to.

Best,
Chris

**Closed by ceaglest** 2019-12-02 20:53 UTC

**Comment by a1nouru** [comment] 2019-12-02 20:57
Thanks :)
