### ISSUE TITLE
Remote video is frozen after returning from background

### ISSUE THREAD

**Issue by etown** [twilio/video-quickstart-ios#388] opened 2019-05-14 05:08 UTC
Frequently after extended time outside of the app, when returning to app remote video view shows a frozen frame. Audio is unaffected. This has been observed on many devices with latest SDK.

**Comment by piyushtank** [comment] 2019-05-14 05:23
@etown Thanks for reaching out. In order to debug this problem, can you provide following information ?

1. The Room SID (`TVIRoom.sid`)
2. The Device and iOS version
3. Video SDK version

Also, is it possible to for you to share the debug logs with us?  

Best,
Piyush

**Comment by vidhyasri2106** [comment] 2019-05-24 06:42
I am getting the same issue often. Did you get to solve this?

**Comment by piyushtank** [comment] 2019-05-24 06:51
@vidhyasri2106 Thanks for reaching out. Unfortunately we haven't been able to reproduce the problem yet. Is it possible for you to provide following when the problem occers - 

The Room SID (TVIRoom.sid)
The Device and iOS version
Video SDK version

Best,
Piyush

**Comment by vidhyasri2106** [comment] 2019-05-24 07:05
Room SID - RMc3454c17f2333f2556061c52356ebba6
Device – iPhone X
iOS version – 12.1.4
Video SDK Version - '2.10'

Also it is automatically getting unsubscribed from Video and Audio track often. Can you please help?



Regards,
Vidhya Sri
Product Developer – Channel Apps Digital & Analytics
HCL Technologies Ltd.,
602/3, ELCOT, SEZ Unit – 1, Sholinganallur,
Chennai – 600 119
Direct: +91 9677523250

https://www.hcltech.com/digital-analytics-services<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hcltech.com%2Fdigital-analytics-services&data=02%7C01%7Cvidhyasri.so%40hcl.com%7Cded1b32f653f478f30d108d5a386b5e5%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C636594721364915827&sdata=vPWPmJ8otwLyTlRPb5r2UGD%2F9%2FAuwESf%2F15p9gP50lQ%3D&reserved=0>

[id:image001.png@01D31687.A1963C50]

**Comment by vidhyasri2106** [comment] 2019-05-27 05:07
Any update on this?

**Comment by piyushtank** [comment] 2019-05-27 05:18
@vidhyasri2106 Thanks for the information and we are investigation the problem. We have observed an issue in our SDK's  network manager module where Wifi to LTE results into one way media, we think the root cause could be the same for the issue that you are observing. 

We are working on the issue and I will get back to you as soon as I have the update. 

Thanks again,
Piyush

**Comment by vidhyasri2106** [comment] 2019-05-27 06:44
Thanks. I will wait for your update.

**Comment by piyushtank** [comment] 2019-06-06 23:26
Hello,

We have found a bug in our infrastructure (media server). It is 100 % reproducible in following network handoff scenario :

1. Alice connects to a Room with Wifi and LTE on.
2. Bob connects to the Room.
3. Alice switches off Wifi
After network handoff, Bob can see and hear Alice, but Alice's can not see or hear Bob. Alice observes frozen screen on her phone.

The fix for this problem has been tested and it is going to be deployed to our media server in a few days. We believe the media server fix should resolve the issue reported by @vidhyasri2106 and @etown on this ticket.

I am sorry for the inconvenience caused by this bug. I will post the update on this ticket once the fix is deployed.

Best,
Piyush

**Comment by vidhyasri2106** [comment] 2019-06-07 06:15
Hi Piyush,
But I am not doing network handoff at all. There is no sim in both devices. Both the devices are connected only with wifi.

**Comment by vidhyasri2106** [comment] 2019-06-07 07:29
Also, I am not getting this issue after returning from the background. I am getting this when the app is in the foreground itself.

**Comment by piyushtank** [comment] 2019-06-07 15:29
@vidhyasri2106 This ticket is specific to network handover and backgrounding scenario. I have deleted your comments to avoid confusion for readers. 
Let use [this](https://github.com/twilio/video-quickstart-swift/issues/392#issuecomment-499773957) ticket for the ARKit freeze issue you are facing without backgrounding and without network handover.

**Comment by piyushtank** [comment] 2019-06-10 19:17
Hello,

Our media server team has deployed the fix for this ticket. The discussed Wifi+LTE -> LTE network handoff scenario should work as expected now. 

Try it out, and Let us know if you have any questions. 

Best,
Piyush

**Comment by NaiyerAghaz** [comment] 2020-04-22 10:53
Yes @piyushtank I am also facing this issue on remote view, how I will fix this?

**Comment by Horatiu** [comment] 2020-05-05 00:37
@piyushtank I am also facing this issue with latest SDK. What is the solution for this? re-enabling the video track when app becomes active as opposed to app entering foreground?

**Comment by piyushtank** [comment] 2020-05-05 01:01
@NaiyerAghaz Apologies for the delay. Can you provide the detailed scenario and the RoomSID when you observed the issue?

@Horatiu Can you provide the detailed scenario and the RoomSID when you observed the issue?

**Comment by Horatiu** [comment] 2020-05-05 02:54
@piyushtank I have fixed it by enabling the video track after applicationDidBecomeActive notification fires as opposed to applicationWillMoveToForeground notification. The way I was able to reproduce was this:

1. In applicationDidEnterBackground notification handler I would set videoTrack?.isEnabled = false and this would disable the video 
2. In applicationWillEnterForeground notification handler I would set videoTrack?.isEnabled = true 

I would notice that the videoTrack would freeze even though at the other end I got the didEnableVideoTrack callback. The reason I need to enable and disable when user moves between app states is because I want a specific UI at the remote participant end and I would implement didEnableVideoTrack/didDisableVideoTrack there to achieve the wanted UX.

To fix it I removed enabling the video track in applicationWillEnterForeground and instead I am enabling it in applicationDidBecomeActive notification handler and that seems to work.

This issue is with the iOS SDK.

**Comment by piyushtank** [comment] 2020-05-06 01:43
@Horatiu You should be able to enable/disable a video track while going to foreground/background.  We would like to fix the issue in SDK but when I tried to reproduce, I couldn't. So, I have created a [branch](https://github.com/twilio/video-quickstart-ios/tree/reproduce-background-bug) on our VideoQuickstart sample app to reproduce the bug. Can you try it out and let me know.

**Comment by Horatiu** [comment] 2020-05-06 16:31
actually the above described 'fix' did not work. If I background one or both participants for 2-3 minutes when I foreground either of them the local track will be 'freezed' even though callbacks that video track was enabled would be received at the other end. I'll try to repro on your branch a little later today.

**Comment by Horatiu** [comment] 2020-05-06 21:12
@piyushtank Upon further investigation I am finding that when moving from background to foreground I get cameraSourceDidFail with error message from AVFoundation: "The operation could not be completed" and that is when the call is placed in this state.

Trying now to recover the call by rebuilding the cameraSource and localVideoTrack from scratch and republishing it when this happens. Will let you know if I manage to fix it that way.

**Comment by raylillywhite** [comment] 2020-05-08 07:14
@piyushtank I'm also experiencing the issue that @etown mentioned. I've filed a Twilio support ticket #4302109 with a call SID, debug logs and a video of it slowly recovering. This seems different than the issue Horatiu is mentioning, since the frozen video is the remote one for me and etown. We can reproduce this every time we background the app for 5+ minutes (but backgrounding the app briefly is fine). After foregrounding, the remote video feed will be frozen for a minute or two before rendering a few frames and freezing again. And each time it freezes, it freezes for a slightly shorter duration until it fully recovers around 5 minutes.

**Comment by piyushtank** [comment] 2020-05-12 00:36
@raylillywhite Thanks. Followed up on the twilio support ticket.

**Comment by halldorlogi** [comment] 2020-05-20 09:04
Any news on a fix here ?

**Comment by piyushtank** [comment] 2020-07-10 22:04
@halldorlogi We haven't been able to reproduce the problem and our team is busy upgrading the webrtc to latest release. If you have room sid and steps to reproduce, we can take a look. Also reproduction with quickstart will be helpful.

**Comment by piyushtank** [comment] 2020-07-17 18:48
Closing the ticket due to no activity. Feel free to reopen if you run into issue or open a new ticket.

**Closed by piyushtank** 2020-07-17 18:48 UTC
Labels: bug, help wanted
