### ISSUE TITLE
Issue: Video Call with Accept and Reject at other user

### ISSUE THREAD

**Issue by Nik20112** [twilio/video-quickstart-ios#147] opened 2017-06-30 19:40 UTC
Hi,
I want to know that is it possible to accept/reject option to other user for accept/reject the video call which is calling by user? Because I have downloaded the demo but there is not this feature available. How can I do it to develop this feature? Please give me suggestion or help.

Thanks
Nikunj

**Comment by Nik20112** [comment] 2017-07-02 08:57
Hi,
Thanks for your feedback. Using Twilio Notify, When I send notification other user, is it available with accept and reject option via push notification? Please let me know.

**Comment by ceaglest** [comment] 2017-07-02 18:05
Hi Nikunj,

Hopefully I can help clarify things a little here. The Android / Twilio Notify example implements one half of the Invite experience. Imagine Alice wants to invite Bob to a video call.

1. Alice and Bob register for push notifications.
2. Alice sends a push notification to Bob inviting him to a Room.
3. Alice joins the Room contained in the notification.
4. If Bob accepts, Bob joins the same Room.
5. Alice and Bob are in a video call.

As far as I understand the Android example does not signal from Bob back to Alice. So, if Bob were to reject the call (by not joining the Room) then Alice wouldn't know about it. In order to support rejecting a call you would need to send an additional notification from Bob back to Alice indicating the acceptance or decline of the Invite.

I'm trying to fill in for Ryan here as I happened to be online. Both Ryan and I are out of the office on Monday but I believe @ptankTwilio can help you out further if you have any more questions.

Thank you,
Chris Eagleston

**Comment by ceaglest** [comment] 2017-07-04 16:12
Hi @Nik20112,

I'm bringing the discussion into your original ticket. We will do our best to integrate push notifications into our QS CallKit example in the future. However, if this is blocking you from getting started now I would suggest that you take a look at the Android example. The server side component is the same regardless of wether you use iOS or Android as the client (just replace FCM with APNS as the notification system).

https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite
https://github.com/TwilioDevEd/sdk-starter-java

Regards,
Chris Eagleston

**Comment by ptankTwilio** [comment] 2017-07-13 01:27
Hi @Nik20112 ,

Let us know if you are running into any issue while using Twilio SDKs to achieve the used case of Accept/Reject the video call.

Thanks,
Piyush

**Comment by iDarshn** [comment] 2018-01-13 11:25
Hi,

How can I add assign user to conference call using twilio voiceAPI?

Please let me know  @ptankTwilio

**Comment by jishindev** [comment] 2018-12-26 07:16
Hey @ceaglest, @piyushtank . How can we show a call screen like WhatsApp/Skype/Telegram etc even when the app is killed or/and the device is locked? Any suggestions on achieving that with Twilio notify?

**Comment by piyushtank** [comment] 2018-12-27 05:05
@jishindev Yes Twilio [Notify](https://www.twilio.com/notify) can solve the problem. When your app is killed, and if iOS receives a push notification when app is killed or in backgroun suspended, iOS will wake your app up. Upon receiving the push notification in your app, in push notification handler, you may want to connect to a Room. 

Let me know if you have any questions.

**Comment by jishindev** [comment] 2018-12-28 06:09
Thanks @piyushtank for the response. How about doing the same in android? Does the app wake up happen there as well?

**Comment by piyushtank** [comment] 2018-12-28 21:02
@jishindev Everyone from our Android team is on vacation at the moment, they will be back next week. My best guess is the behavior would be similar in Android too, but I can confirm with our Android team when they are back and let you know.

**Comment by aaalaniz** [comment] 2019-01-02 20:13
Hey @jishindev 

Yes, the behavior is similar on Android. In the [quickstart example that uses Notify](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) your application will be informed of a push notification (even if your app is killed ) via a subclass of [FirebaseMessagingService](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite). The example shows a notification and sends a local broadcast, but you could implement any logic required in the `onMessage` callback.

Let me know if I need to clarify anything. Thanks!

**Comment by sathishvgs** [comment] 2019-03-24 00:37
Hi @aaalaniz @piyushtank ,
Already, we have tried with `Firebase Push Notification` service. So, my doubt is what is the advantage of using `Twilio Notify` over the Firebase Push Notification.
If we really have any new features we will migrate from `Firebase Push Notification` to `Twilio Notify`.

Thanks,
Sathish Kumar G

**Comment by sathishvgs** [comment] 2019-03-26 01:50
> Hi @aaalaniz @piyushtank ,
> Already, we have tried with `Firebase Push Notification` service. So, my doubt is what is the advantage of using `Twilio Notify` over the Firebase Push Notification.
> If we really have any new features we will migrate from `Firebase Push Notification` to `Twilio Notify`.
> 
> Thanks,
> Sathish Kumar G

Hi @aaalaniz @piyushtank ,
Can anyone check it out this because we have to implement on our end.

**Comment by piyushtank** [comment] 2019-03-26 03:20
@sathishvgs Myself and Aaron we work in Voice and Video SDK team. I have reached out to our notify team to help you out. I will get back to you once I heard back from notify which should tomorrow. But in the meantime, I would recommend going over the [notify-documentation](https://www.twilio.com/docs/notify) to go over the the feature set notify provides. Thanks.

**Comment by jishindev** [comment] 2019-03-26 04:01
Hey @aaalaniz, I've implemented the twilio notify on our app but having delay in getting video notification on Android 9 devices. Any clue why this would be happening?

**Comment by piyushtank** [comment] 2019-03-27 01:24
@sathishvgs if you are using only the Firebase push notifications for making and receiving calls, you may not see additional benefit if you move to Twilio Notify per the TwilioNotify team. Let me know if you have any more questions, however we recommend Twilio Notify for signaling on top of Video SDK.

**Comment by sathishvgs** [comment] 2019-03-27 02:55
@piyushtank 
Thanks for the info.

**Closed** 2020-07-10 22:39 UTC
Labels: help wanted

**Comment by pwndhull** [comment] 2022-08-24 09:15
HI, i have an issue when i send try to a video call and other user accept the call just after that call automatically gets rejected.
this one is specific issue or just a case with me?


Please help me with this.
