### ISSUE TITLE
Can I selectively subscribe to Tracks?

### ISSUE THREAD

**Issue by hasgardee** [twilio/video-quickstart-ios#244] opened 2018-03-20 11:15 UTC
How enable video of the single participant and audio for all room participate ?

**Comment by ceaglest** [comment] 2018-03-20 15:35
Hi @hasgar,

You can have only one Participant share video if you'd like.

Can you be more specific about what you're looking for?

Best,
Chris

**Comment by hasgar** [comment] 2018-03-20 16:51
In a room, there will be have many users..user in the app only want to see a specific user’s video..i know that user’s identity..but user in the app should need to hear voice from every user in the room.
hope you understand..sorry for my bad explanation earlier

**Comment by ceaglest** [comment] 2018-03-20 17:33
Hi @hasgar,

No problem. For now, you could render only the video of the `TVIRemoteParticipant` that you want to see. Audio will be played back automatically.

The issue is that we don't offer Client side selective subscription APIs yet. So, even if you only render a single video Track your client will be automatically subscribed to all Tracks, forcing you to receive video that you don't want.

We're still working on the Client APIs, however we do have server side subscription controls in developer preview at the moment. If you're interested in coordinating subscriptions using a Server side REST API then I can get you setup to try it out.

Best,
Chris

**Comment by hasgar** [comment] 2018-03-20 18:35
Yes, i would like to use rest api for that..please help me to setup that

**Comment by ceaglest** [comment] 2018-03-20 18:53
Awesome, @ktoraskartwilio will be in touch with more info.

**Comment by hasgar** [comment] 2018-03-20 19:17
Okay.. same time all participats video n audio should be visible in web app for admin. So rest api will help to achieve this?

**Comment by ceaglest** [comment] 2018-03-20 20:14
Yes, you can choose which Tracks each Participant is subscribed to. If you have an "admin" role in your app then you can ensure that this Participant gets each and every Track, while regular Participants only get 1 video Track + all audio Tracks.

**Comment by hasgar** [comment] 2018-03-21 10:30
@ceaglest is it possible to get all user's audio only in the app? no need of video in app.. but in web app, admin have to see all user's video at the same time.. in starter project, there is only one remoteParticipant object. so does it mix the audio of many users in the room? if no how to implement that?

**Comment by davidelettieri** [comment] 2019-03-06 11:51
> Yes, you can choose which Tracks each Participant is subscribed to. If you have an "admin" role in your app then you can ensure that this Participant gets each and every Track, while regular Participants only get 1 video Track and all the audio Tracks.


@ceaglest Is there any code example on how to achieve this?

**Comment by ceaglest** [comment] 2019-03-15 02:56
Hi @davidelettieri,

Sorry for the slow response.

> @ceaglest Is there any code example on how to achieve this?

We held a private developer preview for the server side subscription APIs. Based upon the feedback we received, we determined that another iteration on the feature was needed. We are currently refining the APIs, and plan to release a 2nd version in Q2. I'd be happy to share sample code once we get closer to release and start putting together updated public facing docs.

Best,
Chris

**Comment by ceaglest** [comment] 2019-04-25 02:28
Hi @hasgar and @davidelettieri,

We have updated Video iOS to [2.10.0](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#2100-april-24-2019), which gives Clients the ability to connect without subscribing to Tracks. You can try our updated [ReplayKitExample](https://github.com/twilio/video-quickstart-swift/tree/master/ReplayKitExample) for an example of a publish-only Participant. 

The Video team is working on more fully featured Client side subscription rules, and the REST API for later in Q2. I will provide a target release date once we get closer on these features.

Best,
Chris

**Comment by ceaglest** [comment] 2019-11-05 22:07
Hi,

The [REST API](https://www.twilio.com/docs/video/api/track-subscriptions) to manage Participant subscriptions from your Server side application is generally available. I don't have an updated date on when these features might be available in a Client API.

Best,
Chris

**Comment by rskvazh** [comment] 2020-04-27 15:47
@ceaglest Its very popular feature request for Twilio Video - Client-side subscriptions API. Any news about this? We need this for optimized "spatial" room with many participants

**Comment by Ankish** [comment] 2020-05-14 11:38
@rskvazh : We are considering other platforms because of this feature, else there was definitely no doubt we would move ahead with Twilio. But Thanks!

**Comment by ceaglest** [comment] 2020-05-19 22:48
Hi @rskvazh @Ankish,

> Any news about this? We need this for optimized "spatial" room with many participants

We are focusing on adding Bandwidth Profiles to our mobile SDKs at the moment. This should allow you to improve quality in many common multiparty use cases with only client side APIs by switching off tracks that you don't want to receive.

I don't have a timeline on adding client side subscription APIs. When I have more information I will post an issue in https://github.com/twilio/twilio-video-ios to track this request.

Thanks,
Chris

**Comment by Ankish** [comment] 2021-03-03 14:18
@ceaglest :  Just to know, do we yet have a solution to this with latest framework?

**Comment by ceaglest** [comment] 2021-03-03 18:13
Hey @Ankish,

We are working on a release that will add client side track subscription controls. Our current plan is to monitor view visibility and renderer attachment in order automatically switch on/off subscribed tracks.

Would you be interested in trying a pilot later in March? If so, do you have any open support tickets we could speak further on?

Best,
Chris

**Comment by ceaglest** [comment] 2021-03-03 19:28
Hi @rskvazh,

It was an old comment, but is client side track subscription something that you are still interested in?

Best,
Chris

**Comment by Ankish** [comment] 2021-03-04 04:13
@ceaglest : Definitely. We have build the platform over Twilio with intensive buffer processing and lowering the subscription of tracks would give us the CPU bandwidth to improve a lot of our features. One of the most required features for us now. I will be happy to be active on the updates and provide feedback. You can open the ticket and we can follow up on it. Thanks!

**Comment by ceaglest** [comment] 2021-03-04 18:11
Hi @Ankish,

Sounds great. It is definitely not ideal to be subscribing to Tracks, and receiving media that is not being displayed to the user.

Would you mind dropping the ID of the support ticket here so I can follow up with you?

Best,
Chris

**Comment by NarineManukyan** [comment] 2021-03-30 02:19
Following, we have similar issue

**Comment by rskvazh** [comment] 2021-03-30 12:34
Hi @ceaglest
Yes we need it, but on javascript SDK for now.

**Comment by ceaglest** [comment] 2021-03-30 18:13
Hi @rskvazh,

> Yes we need it, but on javascript SDK for now.

There isn't an issue tracking this request but we will be shipping idle track switch off in an upcoming JavaScript release.

I will update this issue once it becomes available.

Thanks,
Chris

**Comment by ceaglest** [comment] 2021-03-30 18:20
Hey @NarineManukyan and @Ankish,

Would either of you be interested in trying a pilot release for iOS with idle video track switch off? If so, please open a support ticket mentioning this GitHub issue and share the ID here.

We expect a pilot release after the Easter holiday. The public version will be released following feedback from internal and external stakeholders on the pilot.

Thanks,
Chris

**Comment by romanfurman6** [comment] 2021-04-05 12:35
Hello, @ceaglest 
I think we have the same issue here.
We need the ability to subscribe to a specific list of tracks for each user.
Like:
In one room we have User_A, User_B, User_C, User_D, User_E, User_F

Where User_A, User_B, User_C can hear & see each other in the same room (but not User_D, User_E, User_F)

User_D, User_E, User_F same ^ (but not User_A, User_B, User_C )

I guess you talked about this case ^, [here](https://github.com/twilio/video-quickstart-ios/issues/244#issuecomment-789948252), right?

Can we get access to that feature now? (JS SDK or RestAPI)

**Comment by ceaglest** [comment] 2021-05-13 23:47
Hi @romanfurman6,

> We need the ability to subscribe to a specific list of tracks for each user.

We are now providing the ability for SDKs (starting with JavaScript) to request that video tracks be switched off in Group Rooms. It's not exactly the same as selective track subscription but I think you will be able to achieve a similar result with most of the device resource savings.

> Can we get access to that feature now? (JS SDK or RestAPI)

Yes, we have just released [twilio-video.js-2.14.0](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2140-may-11-2021) with client track switch off control. You can switch off video tracks if you don't want to display them in your app. We will still send audio but if you don't want to play it you can detach audio tracks from elements.

Best,
Chris

**Comment by ceaglest** [comment] 2022-05-27 21:41
We are now shipping Client Track Switch Off on all platforms. This is the replacement for selective subscription.

**Closed by ceaglest** 2022-05-27 21:41 UTC
Labels: enhancement, help wanted
