### ISSUE TITLE
Published video is delayed (2.0.0-beta4 -> 2.6.0)

### ISSUE THREAD

**Issue by AdiAyyakad** [twilio/video-quickstart-ios#352] opened 2019-01-21 19:06 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

So it seems like there's a significant lag when we upgrade from Twilio SDK v2.0.0-beta4 to v.2.6.0. I haven't quite narrowed it down further than that, but I just wanted to start a dialog and see if y'all have had any similar reports? I'm nervous to upgrade if this is not a known issue or if there is something that we should be doing differently. I followed the QuickStart guide to integrate, but still the issues persist. We have two video feeds streaming from an iOS client as well as a data track to the web. The web also has one video track sending back to iOS as well.

### Steps to Reproduce

Unfortunately it

#### Expected Behavior

Not lag

#### Actual Behavior

A pretty significant lag appears almost instantly. About 1-2 seconds on average between client and web. Lag appears to be one way - web to iOS video stream does not seem to be affected by the same lag.

#### Reproduces How Often

100% of the time when integrated into our product. However, in the quickstart guide and just a slimmed down version of our app I could not reproduce the issue. I assume it's because either our app and the Twilio SDK are fighting for resources (we have a heavy app) or something else that's a little less difficult to detect.

More

#### Logs

Doesn't seem to be anything Twilio specific. Can post anything specific if y'all need any clarification.

### Versions

All relevant version information for the issue.

#### Video iOS SDK

2.0.0 beta 4

#### Xcode

10

#### iOS Version

12.1.4

#### iOS Device

Tried on both iPhone XS Max and iPad Pro

**Comment by ceaglest** [comment] 2019-01-22 18:33
Hi @AdiAyyakad,

2.0.0-beta4 is pretty old, and is not a Generally Available (GA) product. We would recommend that you at least update to a GA version like [2.0.1](
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#201-may-4-2018) from May 4th, 2018.

> but I just wanted to start a dialog and see if y'all have had any similar reports

Not that I am aware of, but we are happy to help.

> We have two video feeds streaming from an iOS client as well as a data track to the web. The web also has one video track sending back to iOS as well.

Which two sources of Video are you sharing? Are you using the TVIVideoCapturer, or TVIVideoSource APIs at this point?

> A pretty significant lag appears almost instantly. About 1-2 seconds on average between client and web. Lag appears to be one way - web to iOS video stream does not seem to be affected by the same lag.

It sounds like the iOS Client is probably overloaded. What does the CPU usage look like during this time? Can you share a Room SID (Room.sid property) so that we can pull server side logs? What about debug Client logs? I can double check if there is any problem with round trip time on the ICE connection, just in case that is somehow the culprit.

Best,
Chris

**Comment by ceaglest** [comment] 2019-01-29 21:00
Hi,

I'm going to be out of the office for the rest of the week, but @piyushtank might be able to offer some advice while I'm gone.

Best,
Chris

**Comment by ceaglest** [comment] 2019-02-16 00:21
Hi @AdiAyyakad,

Did you end up discovering anything new on your side? I'd be happy to take a look at some Room SIDs if you have them handy. Another reason I would recommend upgrading from 2.0.0-beta4 is if you need [compatibility with Firefox 63+](https://github.com/twilio/twilio-video-ios/issues/35).

Best,
Chris

**Comment by patricktemple** [comment] 2019-09-19 20:39
Hi Chris,

I work on this project along with @AdiAyyakad. Sorry to leave this open for a while; we'd kept on 2.2 for a long time, which didn't have the lag, until we were forced to upgrade recently (see https://github.com/twilio/twilio-video.js/issues/714). Now we're on 2.10.1.

We do still see this issue intermittently. It's unpredictable, but seems only somewhat related to overloading of the app. Our app is heavy, but even older devices like iPhone 8 worked fine with the old SDK, whereas we'll now see this problem arise even on an iPad Pro 3rd gen.

Here's a room SID where it happened recently, in case the server logs say anything. The video was almost instantaneous at first and then built up to 2s lag after a while. Typically, refreshing the other page (remote party is web for us) will fix the issue for a while, and then the problem builds up again.
`RM4c9d65b9f97c922b9999b16f18d6adc8`

It gives the impression of a buffer that's queueing up, and then empties out when the page disconnects. I know WebRTC has some frame dropping logic for things like this, but maybe that happens in a place that doesn't catch this?

We haven't yet been able to set up a sample project to repro this, but we can try that if the server logs don't say anything helpful.

Thanks for your help,
Patrick

**Comment by ceaglest** [comment] 2019-09-19 22:11
Hi @patricktemple,

Thanks for the Room SID! 

I had a look at `RM4c9d65b9f97c922b9999b16f18d6adc8` and the browser Participant `PA7d02ebbacbdb84051d8e1c9a482d12e7`. Overall the round trip time on the ICE connection between iOS and JS is fine and usable (<50 ms), but if I look at the video Tracks that are received by the browser there are some very high spikes in RTT (> 1 second). This matches the symptoms that you described.

Is there anything you could share about the capturers that you are using to create the two video Tracks? Are you using TVIVideoSource now that you've upgraded to 2.10.1?

If I can reproduce the delays locally then we can determine if SDK changes are needed to resolve. If the delay is the result of blocking a dispatch worker queue (requiring new worker threads to be created at a critical moment) then the change might need to happen in your code. Lets gather more information to be sure.

Best,
Chris

**Comment by patricktemple** [comment] 2019-09-20 15:02
That makes sense. Even when the video is lagging, the data track always feels fast, unless I'm on a really bad network connection.

Now we're using `TVIVideoSource`. We used to use `TVIVideoCapturer`. We experience this behavior on both of them actually. When we upgraded from `2.2 --> 2.3` we stayed on `TVIVideoCapturer` and that's when this lag began. When we switched over to the new API, it seems roughly equivalent.

If `TVIVideoCapturer` didn't change at all on your side between those two versions, maybe this points to the underlying WebRTC version change that you mentioned?

Codec is VP8. We'd experimented with h264 but preferred VP8 for other reasons. I don't know whether this lag occurs on that; I believe so but it was a while ago that we tried it.

I mentioned we have a heavy app. However there's a feature that "freezes" one of the video feeds, which keeps the track attached but stops sending all frames. It also stops the heavy underlying computation that we do, so the app starts to look like a simple stream from the camera feed. This seems to help the lag somewhat but doesn't solve the problem (it's still not really snappy like our app usually is, running in full, when we're not experiencing this problem.)

A bad network connection exacerbates this, sometimes up to 3 seconds. When I use network link conditioner, heavy packet loss seems more of a culprit than low bandwidth:
- 3Mbps up/down with no packet loss runs fine-
- 10Mbps up/down 15% loss I start to see it
- 10Mbps up/down at 20% loss it gets predictably bad fast

Some added latency is not surprising, but beyond a certain amount I'd just expect dropped frames, so this again gives the impression of a buffer of outbound frames that's queuing up on iOS.

That said, it doesn't only happen on bad connections, and I do sometimes see this even when a speed test shows 50 Mbps+ up and down. That packet loss case might be a red herring, because even on the old SDK I'd start to see serious problems at that threshold.

**Comment by ceaglest** [comment] 2019-09-20 16:55
Hi @patricktemple,

This is really good information, thank you for sharing it. We would like to reproduce the problem on our end and get back to you with our findings. At this point I am thinking that sharing the screen with ReplayKit and the camera while applying network link conditioner might be the best way to reproduce in our own harnesses.

Best,
Chris

**Comment by patricktemple** [comment] 2019-09-21 18:33
Sounds good, thanks for your help! Let me know if there's any more information you need from me.

**Comment by patricktemple** [comment] 2019-10-02 16:08
Hey, have you had any luck reproducing this?

**Comment by patricktemple** [comment] 2019-10-18 01:25
Hi Chris,

I was able to reproduce this in the ReplayKit example of `twilio-video-quickstart` (commit `b74e1c1c4f49ae23f326bd3e53ec750f126d5b2d`), and I made a video to demonstrate this. On the right side, I have an iPhone XR with iOS 13.1.2 with the example app open, in the “browse web” mode. On the left side is the JS sample app, receiving this video.

https://drive.google.com/file/d/15ApB81Xl0ycVZEtwlxlEH2Lxi4g4W38z/view?usp=sharing

I’m on fast wifi (speed test shows 150Mbps up and down). The basic idea is that I’m doing small isolated swipes on the phone, then looking to see when those movements show up on web. Then I do a bunch of fast swiping to “clog up” the frame buffer faster, and then I slow down and look at the lag again with isolated swipes.

0 - 13s: I’m swiping on the phone side to scroll the webpage. This appears on web about 1s later. Let’s call this the baseline latency.
15s: I turn on Network Link Conditioner with high packet loss (20% outbound, 0% inbound) and lower bandwidth (10Mbps up and down).
20-30s: I’m swiping again. Notice the delay isn’t much different yet, despite the worse connection.
30-44s: I’m swiping fast for a while, just trying to force a bunch of frames to go through. Finally the web settles on the same image as iOS.
44-53s: Now I’m back to single swipes. Notice it takes 3s for the changes to show up on web.
56-1:09s: More fast swiping for a while to send more frames.
1:23s: I swipe once, and it takes 15s for the frame to propagate through.
1:53s: I turn off network link conditioner, bringing back normal internet speeds.
2:00s: I swipe again, and it still takes 3s for the video to go through. So even though we’re back on a fast connection, there’s a hangover from the long session from the slow network.

So the overall picture here is of a problem that gets worse as the session goes on. It sometimes happens on good connections, but it’s much worse on bad ones. Maybe it’s a memory leak, maybe it’s a frame buffer that’s filling up. Sometimes after a while of this, the lag will instantly disappear, as though a buffer was cleared. Then it usually starts to accumulate again.

Thanks,
Patrick

**Comment by spalmertwilio** [comment] 2019-10-18 03:25
Hi Patrick,

Chris will be back in the office next week.  Unfortunately, I am unsure of where he is as far as reproducing the issue.  Did you perchance grap a debug client-side log of the above, and a Room SID?

Best,
Stephanie

**Comment by patricktemple** [comment] 2019-10-19 15:47
Hi Stephanie,

The room SID was `RM7f84fed86172e5a3fb0c78e91062bec3` but I didn't grab client logs. Note that I kept that room open a long time as I figured out how to reproduce this in the sample app, so the two participants connected and disconnected many times during that room. In the video I shared above, I had just freshly joined the room again on both sides, and I'm pretty sure it was the last thing I did in that room before I left it and it auto-closed 5 minutes later (so I'd expect the last 10 minutes of the logs to contain the events of the video).

Thanks,
Patrick

**Comment by ceaglest** [comment] 2019-10-29 23:29
Hello Patrick,

I had a look at the Room SID, and the video that you shared. I see that with 20% outbound packet loss in network link conditioner, the audio track reports packet losses every few seconds. It seems that this loss is not being recovered consistently with in-band FEC because the RTT of the audio Track sometimes increases when it occurs. One limitation with In-Band FEC is that the redundant information can only recover the previous lost audio packet, and not packets before that.

On the video side, the resolution stays fixed (due to screencast mode) but the encoder is dropping a lot of frames. This is also leading to the build up of delay, and the video sender being very conservative. It is in an imbalanced scenario where even retransmissions, or small RTCP packets can be lost, but the other party is still pushing their audio/video down with no packet losses. At this time the paced sender is also being even more conservative in writing packets (my supposition without seeing client logs) because it sees 20% fixed losses even after reducing the number of packets sent. At the time you are not touching the screen, the ReplayKit VideoSource is capturing at 4 fps. Maybe the rate of resends of still frames needs to be adjusted?

I'm reproducing it on my end next. My first goal is to figure out if In-Band FEC is being applied correctly to the audio track to account for the losses in this environment. After that I'll be looking into video.

Best,
Chris

**Comment by patricktemple** [comment] 2019-10-30 02:38
Thanks Chris. With this repro video I made using the ReplayKit example, I'd just note that it qualitatively looked very similar to the issue we were seeing in our own app, and we do use our own custom `TVIVideoSource`. But there might be some details that aren't the same (e.g. screencast mode, which as I understand it, is particular to that ReplayKit example and not in the SDK itself). In our app, we use the default output format on the sink, rather than setting it the way that example does.

I can also try to reproduce it in the Webview example if that's helpful, since I see that also uses the same API.

I did also run this again in our own app, setting log level to debug. I saw the delay happening but nothing interesting happened in the client logs, just messages like "remote participant connected". I could bump that down to trace if that's helpful too, and save them and forward them along.

**Comment by patricktemple** [comment] 2019-10-30 14:39
When you said the encoder is dropping a lot of video frames and the leads to the delay. I assume this could cause delay if the encoder retries all the lost frames until they're successfully transmitted. Is that how it works? Or might it accept that some video frames have been lost and, noticing a big skew building up in the timestamp, skip to the more recent frames in order to minimize lag? I'm not sure what level of control is available here, but in our case a timely but choppy video would be preferable to a smooth and delayed one.

**Comment by patricktemple** [comment] 2019-10-30 21:03
`RMf8cb4933155c0e548fd8fa2e77e3a97d` is a room that had this issue naturally, without Network Link Conditioner. Max lag that I saw was about 2.5s. At the time, my Wifi speed test showed 45Mbps down, 100Mbps up,

**Comment by patricktemple** [comment] 2019-11-01 00:33
Did a few more tests here, making a simple example that creates an `AVCaptureSession` and sends the frames straight to a `VideoSink`, with Network Link Conditioner set to high packet loss.
- If `screencast=true` then I get this classical lag behavior that I described, with high quality video frames that start out smooth and gradually slow down.
- If `screencast=false` then I still start out with high quality video frames and a smooth frame rate. Then the video gets downscaled several times to pretty small dimensions. Frame rate stays good until it reaches the smallest size, and then the frame rate starts to get worse and worse, and some lag accrues.

If I use a `CameraSource` the behavior seems the same as the latter.

**Comment by ceaglest** [comment] 2019-11-01 04:15
Hi @patricktemple,

> Once the call begins and it's fallen into one of these two buckets, it keeps that behavior through the call.
> Does this sound plausible?

Yes it's certainly possible that some bad assumptions are being made by the media engine in this multi-track case. For now a workaround of not mixing might be the best option.

You are correct about the screencast behavior, there is a very different allocation of bits in each operating mode for the sender. In the screencast mode, the goal is to have the highest picture quality and to not downscale the content. So, when packet loss occurs dropping current frames so that previous frames can be recovered is probable. This was happening in your Room SIDs and in my own tests, which contributed to extra delay.

> If I use a CameraSource the behavior seems the same as the latter.

Yes, since we don't ever enable screencast mode in TVICameraSource.

> If we just set screencast to false for both, it does seem to solve lag issue, though there is the subtler underlying issue of the video resolution getting worse and worse as the call progresses.

I'm curious is the issue of video resolution getting worse something that can occur under real network conditions or only with network link conditioner in your tests? I don't think it is realistic enough, since the packet losses remain constant despite WebRTC's attempts to reduce them. Eventually the bandwidth estimate is very low leading to downscaled video.

I wonder if there is a better way to simulate on macOS (or iOS), perhaps using `pfctl` directly? We have more powerful tools available to simulate networks on Linux I am afraid.

Anyways, I have spent some time with network link conditioner. I can see that In-Band FEC for audio is working as well as can be expected under packet loss conditions. I am now doing some analysis of packet loss for video samples as well. We recently enabled [FEC for Video in Group Rooms](https://www.twilio.com/changelog/fec-forward-error-correction-group-rooms), so I believe P2P / Group Participants should be on fairly equal footing when it comes to handling packet loss at this time.

When I look at the RTP I am hoping to see the sender start compensating for the packet loss by sending FEC packets for video at a rate so retransmissions are not needed. Besides reducing the quality at a given bitrate, I wouldn't expect massive delays or downscaling to be needed. However, the choice to use FEC depends on a number of factors including the RTT between sender/receiver and this theory isn't matching my own experience or yours.

I'll share some more when I can perform a few more captures. In the meantime, I wonder if it might make sense to not mix the screencast / non-screencast tracks?

Best,
Chris

**Comment by patricktemple** [comment] 2019-11-01 11:42
Yep, I'll switch both to non screencast. I wonder too whether the downscaling would only be happening on Network Link Conditioner since it may not be that representative of real network conditions. I'll let you know how that goes.

At the same time, gradually scaling down the bitrate to deal with packet loss strikes me as a strange behavior. I guess this could work if the packet loss rate in a real network is not constant but would be reduced if the bitrate is lower? In my sample app case, the video quality is actually quite good at the beginning of the session, despite the high packet loss rate. So it seems like the efforts to adapt to the network condition are what's making it worse over time than it needs to be.

**Comment by patricktemple** [comment] 2019-11-08 19:55
Quick update, we did switch both to non-screencast and it has been a dramatic improvement. No buildup of video lag, even on bad networks, where instead it'll sometimes freeze and drop frames but pick back up with at most 0.5s delay (as I'd hope).

There probably still is an underlying issue of the video resolution being downscaled too aggressively, especially under contrived network conditions, but that seems recoverable (sometimes after quality drops a lot, it'll come back up again, though not to the original level). But for us the urgency is much lower now that we've fixed the problem with the delay.

Thanks for all your help, Chris.

**Comment by ceaglest** [comment] 2019-11-08 21:00
Hey Patrick,

You are welcome. I'm glad to hear that you have some relief on the delay issue! I'm keeping this ticket open so that we can retest the scenario with future versions of Twilio Video.

Best,
Chris

**Comment by piyushtank** [comment] 2021-01-29 20:36
Closing an old ticket. Feel free to reopen or file another ticket if you run into any issues.

**Closed by piyushtank** 2021-01-29 20:36 UTC
Labels: help wanted

**Comment by ceaglest** [comment] 2021-01-29 21:02
Twilio Video 4.0 is based upon WebRTC 83 and re-enables simulcast of screencast content. This issue should not occur in 4.0.
