### ISSUE TITLE
ReplayKit broadcasting not working with ongoing video calling

### ISSUE THREAD

**Issue by BhoomiPatel1** [twilio/video-quickstart-ios#584] opened 2021-01-11 12:59 UTC
>I have integrated ReplayKit for screen sharing to room participant can share screen while on going video call, but broadcast it's not working with on going call and also screen share not working in replay kit example project.

**Step which I have followed**
1). create token
2). connect room with particular access token
3). two participant joined that room 
4). now I want to share my screen to other participants of room

>other things are working perfectly with Twilio but only broadcast isn't working.

**Xcode**
11.12.2

**OS Version**
12.4.8

**Comment by timrozum** [comment] 2021-01-11 16:34
Hi @BhoomiPatel1,

I would like to confirm you are able to get the screen broadcast working correctly with the quickstart code. Can you use `ReplayKitExample` to start a broadcast and then use `VideoQuickStart` project to view the screen capture? After you launch `VideoQuickStart` enter `Broadcast` for the room name and connect. You should see the video from the screen capture at that point.

Please let me know how that goes!

**Comment by BhoomiPatel1** [comment] 2021-01-18 06:59
I have used Twilio's ReplayKitExample for screen sharing but its not working , I want to start broadcast while already 2 or 3 participant joined same room

**Comment by timrozum** [comment] 2021-01-19 17:18
Hi @BhoomiPatel1,

Did you get `ReplayKitExample` (screen capture app) working with the `VideoQuickStart` (viewer app) as a basic test to share video to another participant? You should be able to just drop in Twilio access tokens to these projects and then run them without modifying any real code. I think it would be best to get this simple case working first and then determine how it is different from your specific implementation. 

The number of participants shouldn't impact the screen capture so the issue is probably either related to sending or receiving the screen track. Check the track name, verify it is set to enabled, and is published. On the receiving side you could print information about remote participants to debug tracks.

Thanks!

**Comment by timrozum** [comment] 2021-08-24 19:08
Hi @BhoomiPatel1, 

I'm going to close this issue but if you have more questions please feel free to respond here.

**Closed by timrozum** 2021-08-24 19:08 UTC
Labels: question, ReplayKit
