### ISSUE TITLE
ReplayKit & UIScene: Assertion when calling RPSystemBroadcastPickerView

### ISSUE THREAD

**Issue by ganga1120** [twilio/video-quickstart-ios#438] opened 2019-10-22 06:21 UTC
Hi

   We are implementing the screen broadcasting functionality using Replaykit Twilio SDK and integrated the SDK successfully into our project. But when we run our application on the iOS device getting the following error.

**[Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.**

could you please help me with this?

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[3.0]

#### Xcode

[11.0]

#### iOS Version

[13.1.2]

#### iOS Device

[ iPhone 7]

Thanks,
Ganga

**Comment by ceaglest** [comment] 2019-10-22 17:46
Hi @ganga1120,

> [Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.

It sounds like you have partially adopted UIScene in your Xcode 11 app. You'll need to complete the transition to prevent this assertion.

A UIWindowScene is already associated with a UIScreen at creation time (from your .plist or via `[UIApplication requestSceneSessionActivation:userActivity:options:errorHandler:]`). If you have a window and want it to be associated with a screen, you can call `-[UIWindow setWindowScene:]` providing the scene that was already created for the screen.

I hope that was helpful. If not, would you mind sharing the code where you are setting the screen?

Regards,
Chris

**Comment by ceaglest** [comment] 2019-11-05 22:04
Let us know if you need any more help. Thanks!

**Comment by SebOh** [comment] 2020-03-04 10:43
Hi,

I have the same issue currently and not pretty sure what it means to "complete the transition to prevent this assertion."

I setuped a new project with xCode for targeting iOS 13. I have a AppDelegate and SceneDelegate class present and I'm a bit lost how to get ride of the error. Would it be possible to get some more information of how to address the issue?

Thanks

**Comment by ceaglest** [comment] 2020-03-05 01:01
Hi @SebOh,

I wasn't able to reproduce the issue raised by the original poster. Are you explicitly calling `[UIWindow setScreen:]` in your app which has a SceneDelegate? It's not allowed when you are using UIScene, and having a SceneDelegate opts into UIScene on iOS 13.

Could you share the call stack for the main thread when the assertion occurs?

Best,
Chris

**Comment by SebOh** [comment] 2020-03-05 09:08
Hi @ceaglest,

I double checked and I'm no calling the method [UIWindow setScreen:]  inside the code.

Regarding the stack I'm not sure how to get it. This is basically the only message I get. If you know a trickt to get more info about it I'm happy to try it out.  

2020-03-05 10:01:44.014805+0100 app[1643:22397] [Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.

Thanks
SebOh

**Comment by ceaglest** [comment] 2020-03-05 19:48
Hey @SebOh,

We would like to help, but how can the assertion be reproduced? Is it possible to modify the ReplayKitExample to throw the assertion, or is there some other code that you could share?

Best,
Chris

**Comment by emraz** [comment] 2020-03-29 11:29
Hi @ceaglest 
I have faced the similar problem, I have attached here my public code link. Please check and help me to resolve the issue. Thanks 

https://github.com/emraz/ERScreenRecord

**Comment by ceaglest** [comment] 2020-03-30 16:12
Hi @emraz,

I can take a look at the code, but can you please provide a stack trace when the assertion occurs?

You can get a trace by typing `bt all` in Xcode's debug console. As far as I know this issue isn't reproducible with our sample code, so a trace would be really helpful to debug it.

Best,
Chris

**Comment by emraz** [comment] 2020-03-30 16:48
Hi @ceaglest 
I have tried by typing bt all in Xcode's debug console, but didn't get anything. I have given my code link in first comment, you can easily reproduce. When I press "Start Broadcast" button, nothing happen just shown the message in debug log. 

ERScreenRecord[5480:1629564] [Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.

**Comment by ceaglest** [comment] 2020-03-30 16:55
Hey @emraz,

Does setting an exception breakpoint catch the assertion? Once that fires, use `bt all`.

![Screen Shot 2020-03-30 at 9 54 34 AM](https://user-images.githubusercontent.com/1302577/77939829-96303e80-726c-11ea-8328-715200fc2684.png)

Thanks,
Chris

**Comment by emraz** [comment] 2020-03-30 16:59
Hi @ceaglest 
Nothing!! Exception breakpoint doesn't catch.

**Comment by ceaglest** [comment] 2020-03-30 17:14
Okay, thanks for trying it! I will checkout the code that you posted and try to repro locally.

**Comment by ceaglest** [comment] 2020-03-30 21:30
Hi @emraz, @SebOh, @ganga1120,

I was able to reproduce the issue with the project provided by @emraz using iOS 13.3.1. There seems to be a bug with RPSystemBroadcastPickerView which occurs after opting into UIScene. In fact, it seems like ReplayKit just doesn't support UIScene properly which is sad because it is Apple's recommended path forward as of iOS 13.

The reason why our ReplayKit example is not impacted is because it does not opt into UIScene yet. If you must have ReplayKit support then you may need to consider not using UIScene, and going back to UIApplicationDelegate. This can be done by removing the "Application Scene Manifest" from your main application's Info.plist file and implementing the app lifecycle events in your UIApplicationDelegate instead of UISceneDelegate. If you require UIScene features and ReplayKit then you might be out of luck for now.

I have responded to the related [Apple developer forum post](https://forums.developer.apple.com/thread/122211). Once I have some time to investigate further, and reproduce in iOS 13.4 I would like to file a feedback with Apple.

Best,
Chris

**Comment by ceaglest** [comment] 2020-03-30 21:52
Hello,

Since the offending code is in ReplayKit.framework and doesn't appear to throw I set a symbolic breakpoint. The offending class seems to be private (RPModalSystemPresentationWindow). Here is the stack trace from @emraz's sample project:

```
bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001bd5ed8bc UIKitCore`-[UIWindow setScreen:]
    frame #1: 0x00000001e30ae38c ReplayKit`-[RPModalPresentationWindow init] + 184
    frame #2: 0x00000001e309eefc ReplayKit`-[RPBroadcastPickerStandaloneViewController presentAnimated:completion:] + 88
    frame #3: 0x00000001e309f9b8 ReplayKit`__45-[RPSystemBroadcastPickerView buttonPressed:]_block_invoke + 180
    frame #4: 0x00000001e309eddc ReplayKit`__120-[RPBroadcastPickerStandaloneViewController loadViewControllerWithBundleIdentifier:showMicrophoneButton:withCompletion:]_block_invoke_2 + 432
    frame #5: 0x0000000104a597fc libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #6: 0x0000000104a5abd8 libdispatch.dylib`_dispatch_client_callout + 16
    frame #7: 0x0000000104a68c34 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1316
    frame #8: 0x00000001b94a05e4 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #9: 0x00000001b949b5d8 CoreFoundation`__CFRunLoopRun + 2004
    frame #10: 0x00000001b949aadc CoreFoundation`CFRunLoopRunSpecific + 464
    frame #11: 0x00000001c343b328 GraphicsServices`GSEventRunModal + 104
    frame #12: 0x00000001bd5a863c UIKitCore`UIApplicationMain + 1936
    frame #13: 0x000000010473e1f0 ERScreenRecord`main at AppDelegate.swift:12:7
    frame #14: 0x00000001b9324360 libdyld.dylib`start + 4
  thread #4
    frame #0: 0x00000001b9241758 libsystem_pthread.dylib`start_wqthread
  thread #6, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x00000001b92f8634 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001b92f7aa0 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x00000001b94a0288 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame #3: 0x00000001b949b3a8 CoreFoundation`__CFRunLoopRun + 1444
    frame #4: 0x00000001b949aadc CoreFoundation`CFRunLoopRunSpecific + 464
    frame #5: 0x00000001b97da784 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
    frame #6: 0x00000001b97da664 Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 88
    frame #7: 0x00000001bd640e80 UIKitCore`-[UIEventFetcher threadMain] + 152
    frame #8: 0x00000001b990b09c Foundation`__NSThread__start__ + 848
    frame #9: 0x00000001b923dd8c libsystem_pthread.dylib`_pthread_start + 156
  thread #8
    frame #0: 0x00000001b9241758 libsystem_pthread.dylib`start_wqthread
  thread #9
    frame #0: 0x0000000000000000
```

Best,
Chris

**Comment by emraz** [comment] 2020-03-31 02:08
Hi @ceaglest,
Thank you so much for your investigation.  I will try using UIApplicationDelegate only.

**Comment by emraz** [comment] 2020-04-06 03:29
> Hi @emraz, @SebOh, @ganga1120,
> 
> I was able to reproduce the issue with the project provided by @emraz using iOS 13.3.1. There is a bug with RPSystemBroadcastPickerView which occurs after opting into UIScene. In fact, it seems like ReplayKit just doesn't support UIScene properly which is sad because it is Apple's recommended path forward as of iOS 13.
> 
> The reason why our ReplayKit example is not impacted is because it does not opt into UIScene yet. If you must use RPSystemBroadcastPickerView then you should consider not using UIScene, and going back to UIApplicationDelegate. This can be done by removing the "Application Scene Manifest" from your main application's Info.plist file and implementing the app lifecycle events in your UIApplicationDelegate instead of UISceneDelegate. If you require UIScene features and ReplayKit (specifically RPSystemBroadcastPickerView) then you might be out of luck for now.
> 
> I have responded to the related [Apple developer forum post](https://forums.developer.apple.com/thread/122211). Once I have some time to investigate further, and reproduce in iOS 13.4 I would like to file a feedback with Apple.
> 
> Best,
> Chris

I have implemented according to your suggestions and its work fine. Thanks a lot.

**Comment by lo-fo** [comment] 2020-04-21 08:02
The issue is unfixed as of [XCode 11.4.1] [iOS 13.4.1] ?
Did anyone find a way to get around it ? I was wondering if method swizzling some private APIs could be helpful here.

**Comment by timrozum** [comment] 2021-01-29 21:10
I have tested on iOS 14.2 and this seems to be fixed now.

It seems like not using UIScene may be the best solution for older versions of iOS.

**Closed by timrozum** 2021-01-29 21:10 UTC
Labels: help wanted
