### ISSUE TITLE
Mitigating Blurriness & Green Screens

### ISSUE THREAD

**Issue by jvmontes** [twilio/video-quickstart-ios#378] opened 2019-04-22 19:33 UTC
### Description

Hello there, me again. Thank you for your support earlier on finding solutions we could use with ReplayKit. As we continue to test and provide the best experience we can, as we were doing with our earlier implementation, we now see a defect where participant screens intermittently flash bright green. How can we avoid the green screen issue? And how can we get blurriness to clear quickly and consistently? 

### Steps to Reproduce

1. Start the video stream
2. Navigate through different parts of the application (using segues, general updates from UIControls)
3. Observe the participant

#### Code

We are leveraging the existing `ReplayKitVideoSource.swift` provided to stream our meeting. 

#### Expected Behavior

Participants should never see a flash of green on their screen. Blurry participant screens should also be consistently resolved quickly. 

#### Actual Behavior

Participants intermittently see green flashing on their screen. Participant screens may stay blurry for up to several seconds, or consistently appear blurry. May go back and forth from being blurry, to being clear, to being blurry again for several seconds, and never quite reach the level of pristine display it may initially have, or may take several seconds to display the level of pristine picture quality. 

#### Reproduces How Often

10% Green Screen. Have noticed that it hasn't happened as much when I lowered `kDesiredFrameRate` to `30` from `120`. 

30% Blurriness Issue. 

### Versions

All relevant version information for the issue.

#### Video iOS SDK

2.7.0

#### Xcode

10.1

#### iOS Version

11.3.1

#### iOS Device

A1584 iPad Pro

![BlurryUI](https://user-images.githubusercontent.com/2475719/56521892-81e7ab80-650b-11e9-9916-5fb1a4c1c636.png)

![ClearUI](https://user-images.githubusercontent.com/2475719/56521915-8744f600-650b-11e9-96ca-c19855cd6d4f.png)

**Comment by ceaglest** [comment] 2019-04-24 03:54
Hi @jvmontes,

Sorry that we did not get a chance to cover your question today, but we will dig into it tomorrow.

Off the top of my head, there are several reasons why the resolution of the video might drop, including constrained sender or receiver bandwidth. If its very important that spatial resolution be maintained then you can use the [screencast mode](https://github.com/twilio/video-quickstart-swift/blob/master/ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift#L49) in ReplayKitVideoSource.

I will see if @paynerc can help on this one, as he is pretty familiar with your use case.

Best,
Chris

**Comment by jvmontes** [comment] 2019-04-24 20:07
Hi @ceaglest , 

Thank you for your reply. I feel silly now, it seems that setting `screencastUsage` fixed our blurriness issue, thanks so much. 

We still intermittently see a green screen mask the entire display before clearing up shortly after. In my opinion, this isn't a showstopper but definitely a jarring experience on the participant's end. Have you seen anything regarding this or have ways to mitigate it?

Thanks again, we're almost at the finish line!!  🙌

**Comment by paynerc** [comment] 2019-04-24 20:26
Hey @jvmontes,

As @ceaglest mentioned, it would be helpful to know a couple things about your setup. Specifically,
* What video codec are you using?
* Are you using a Group or Peer to Peer room?
* How many participants are in the room when you are seeing the green screen?

Also, and room sids for when you have experienced this issue could also be useful. You could send those to the support email, reference me and this GitHub issue and it should find its way to me.

Thanks!

Ryan

**Comment by jvmontes** [comment] 2019-04-24 21:17
Hi Ryan,

We are using the VP8 Codec.
I'm not sure if we are using Group or Peer to Peer rooms, I've looked around in our front-end and back-end code and can't find anything. Do you know how I can find this information?
I am able to reproduce the green screen issue by just connecting a single participant. 

I've sent an email to Alex from the support team with the room SID.

Thanks!
Jorge

**Comment by paynerc** [comment] 2019-04-29 14:34
@jvmontes,

Just a follow up on this ticket here, I have responded to you through the support system. We can leave this issue open in the meantime until we determine the issue and then post a public reply about what we find. We can continue to work through your open support ticket until that time.

Thanks!

Ryan

**Comment by paynerc** [comment] 2020-02-05 14:23
@jvmontes,

I know that we had worked offline through the support ticket. Are you still seeing issues with this or is it OK to close this issue?

Thank you,

Ryan

**Comment by GPITwilioMonitor** [comment] 2020-04-06 14:59
Hi all,

I'm part of a new team that has taken ownership of this feature, apologies for the silence these past couple months. Can we re-open this ticket? I can confirm that the green screen issue is still present for our application.

To keep you up-to-date on some of the specs:

iOS codebase (this is where we broadcast from) and devices:
- Twilio Video SDK iOS 3.0
- Video codec: Vp8Codec with simulcast
- Xcode 11.3.1
- iOS Version 13.x
- Primary iOS devices using the app: iPad 5th and 6th gen, iPad Pro 2nd gen
- ReplayKitExample code: for streaming video, we implemented this example code that is available on your quickstart, and pulled the latest on 1/20/20.
- Not sure if this is a Group or Peer to Peer room, but the Twilio Room object is a TVIRoom.

We use a web browser for the participants (which receives the video stream):
- Twilio Video SDK Javascript 2.2.0
- Chrome (recommended browser) version 80.0.x

The issue:
- Intermittent green screen flash
- Issue tends to be more prevalent the more participants there are in the room. Definitely present with only 1-2, but more so with 5-6.

**Comment by GPITwilioMonitor** [comment] 2020-04-09 13:55
I've also opened a ticket via the Twilio support center regarding this issue (#4112106).

Here is a screenshot of the green screen that is shared within the ticket:
https://p14.zdusercontent.com/attachment/5194/dpeBEmwm2UzCjrAeOtYall80Q?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..eN4-NJi3j_loLEzqcYLjoQ.Xo2YOj9AzpHy9Vl9l9YrX52vRyJPLtl4QUT6X-EHwZvoiLPFNfSedMkWjpUet2hMCzxIdGp4RBd4walD90wKMiINh161O1BwG_flkP43-qdn8MOTXnOG3jM0fA-bjdic8WSCKq8b3rCw1CLWByli_yJUZk1C51fQxo_NCNAmmrg3ppyUnKhhXFLB-9-5I-wgOX_V4qisynLfykluWMYqBb6Qx_T-pZ7jB5WVBiEPrRCEBZ1l8HUTTWix3jKw0gnuLKm-uT4QCHiWqVsHh3I7Rg.RmxyehqI1ygKG8iDp9bG2A

**Comment by paynerc** [comment] 2020-04-22 17:50
@GPITwilioMonitor,

I'm sorry you are still experiencing this issue. I will reopen this ticket and review the support ticket you mentioned above. I will get back to you shortly.

Ryan

**Comment by piyushtank** [comment] 2020-04-27 04:54
@GPITwilioMonitor - Thanks for reaching out. Yes, we are able to reproduce the bug using our ReplayKit Sample app. We think the problem happens due to the packet loss. Our observation is problem occurs when frame rates supplied by the VideoSource spikes. The problem may disappear by tweaking the [frame rate](https://github.com/twilio/video-quickstart-ios/blob/master/ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift#L63) to a higher number say 20fps or a higher number,  the downside is it may cause higher cpu utilization and higher battery usage - you may want to try it out to see if you see any improvements. 

On our side, we are investigating if our infrastructure media engine or any improvements needs to be made in our ReplayKitVideoSource. I will keep you posted. 

Let me know if you have any questions.

**Comment by GPITwilioMonitor** [comment] 2020-04-27 20:38
Hi @piyushtank - I'm glad you were able to reproduce the issue on your end. In the past we did experiment with differing frame rates - nothing effectively eliminated the green screen flash.

I also should call out: we don't actually use any of the retransmission logic. We encountered a crash a while back from within the `dispatchRetransmissions` function. Additionally, the `ExampleCoreAudioDeviceGetCurrentQueue` which populates the `videoQueue` variable  is using a long-deprecated API to retrieve the current queue. For these two reasons we decided to implement our own mechanism to ensure continuous frames are being sent, and we cut out all of the code from ReplayKitVideoSource relating to retransmissions (including the `kFrameRetransmitIntervalMs` variable you mentioned above). 

I can share our version of ReplayKitExampleCode.swift, what's your email address so that I can send this to you privately?

Thanks,
Erin

**Comment by piyushtank** [comment] 2020-04-27 20:41
@GPITwilioMonitor Sure, I would be happy to take a look at your version of `ReplayKitExampleCode.swift`. My email address is ptank@twilio.com.

**Comment by piyushtank** [comment] 2020-05-01 20:27
@GPITwilioMonitor We did some investigation on our side - the green screen issue occurs because of the packet loss. This could happen when send bitrate spikes. If you set the minimum fps, it may help little as the encoder optimizes bitrate usage when the still screen image is being sent out upon a higher fps. We think setting the minimum bitrate parameter should help. I have created feature request to add APIs to set screencast min bitrate in our SDK.

For now, increasing the minimum fps is the best options which unfortunately will not solve the problem completely but may help little.

**Comment by paynerc** [comment] 2021-01-19 17:55
@GPITwilioMonitor,

Are you still experiencing issues related to this ticket?

Ryan

**Comment by GPITwilioMonitor** [comment] 2021-01-20 16:29
Hi Ryan, thanks for checking in.  We are actively using the Group Room feature in our production release and have not heard complaints about the green screen.   

Mike

**Comment by paynerc** [comment] 2021-01-20 16:30
Thanks wonderful news. Thanks for responding. I will close out this issue.

Ryan

**Closed by paynerc** 2021-01-20 16:30 UTC
