### ISSUE TITLE
Recording interrupted by multitasking and content resizing on ReplayKitExample

### ISSUE THREAD

**Issue by JulienLevallois** [twilio/video-quickstart-ios#405] opened 2019-06-24 16:48 UTC
I got this error "Recording interrupted by multitasking and content resizing" when i launch ReplayKitExample.

Do you know why ?

Thanks

**Comment by piyushtank** [comment] 2019-07-25 01:32
@JulienLevallois We think this is a bug in ReplayKit. We have reached out to apple and filed a radar for this.

This is a duplicate of https://github.com/twilio/video-quickstart-ios/issues/322. Can we close this ticket and track it at one place.

**Comment by ceaglest** [comment] 2019-07-25 01:44
Closing as a duplicate. Please use #322 instead.

**Closed by ceaglest** 2019-07-25 01:45 UTC
